### PR TITLE
X

### PR DESCRIPTION
**Pull request by mcampa**

### CODE REVIEW

**Comment by mcampa** [comment]
Hello

**Comment by mcampa** [comment]
Here is your bundle zipPath/url

**Comment by mcampa** [comment]
Here is your bundle http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/76a7d55874466a96d3e4b40af2f53b6126c4909f/bundle.zip

**Comment by mcampa** [comment]
Here is your [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/5ec3c152bb50f3728f1fe941859bc7300a577c93/bundle.zip) :bowtie:

**Comment by mcampa** [comment]
hold on tigh! I'm creating a bundle for you :bowtie:

**Comment by mcampa** [comment]
Here is your [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/f33c7472a530a4e67c8e08b239d46cbe0ea9bd90/bundle.zip) :sunglasses:

**Comment by mcampa** [comment]
hold on tigh! I'm creating a bundle for you :bowtie:

**Comment by mcampa** [comment]
Here is your [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/4386397c910cb3c77ba6c20693d2f2ab7a69c9af/bundle.zip) :sunglasses:

**Comment by mcampa** [comment]
hold on tigh! I'm creating a bundle for you :bowtie:

**Comment by mcampa** [comment]
hold on tigh! I'm creating a bundle for you :bowtie:

**Comment by mcampa** [comment]
Here is your [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/bee06b03a73b7bea6507348eb7b1b3b882da50ee/bundle.zip) :sunglasses:

**Comment by mcampa** [comment]
Here is your [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/cd7a4d4d33b4ae11003af5c3a9c8ba7ff878b800/bundle.zip) for commit cd7a4d4 :sunglasses:

**Comment by mcampa** [comment]
[
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/tools/toolkit.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/settings/global/global.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/settings/normalize/normalize.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/settings/foundation/foundation.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/settings/bigcommerce/bigcommerce.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/vendor/foundation/foundation.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/utilities/utilities.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/vendor/normalize/normalize.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/components/components.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/slick-carousel/slick/slick.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/slick-carousel/slick/slick-theme.scss"
    }
  }
]

**Comment by mcampa** [comment]
[
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/tools/toolkit.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/settings/global/global.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/settings/normalize/normalize.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/settings/foundation/foundation.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/settings/bigcommerce/bigcommerce.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/vendor/foundation/foundation.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/utilities/utilities.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/vendor/normalize/normalize.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/@bigcommerce/citadel/dist/components/components.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/slick-carousel/slick/slick.scss"
    }
  },
  {
    "type": "missingScss",
    "data": {
      "file": "node_modules/slick-carousel/slick/slick-theme.scss"
    }
  }
]

**Comment by mcampa** [comment]
Hold on tigh! I'm creating a bundle for you :bowtie:

**Comment by mcampa** [comment]
Generating bundle for 7cb9608

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/7cb96087a1be3a8a4e7d106afa2367c562eb7185/bundle.zip) for commit 7cb9608

**Comment by mcampa** [comment]
Generating bundle for 89bbdb5

**Comment by mcampa** [comment]
Generating bundle for 15a0409

**Comment by mcampa** [comment]
Generating bundle for 1c7d29c

**Comment by mcampa** [comment]
Generating bundle for d4d758d

**Comment by mcampa** [comment]
Generating bundle for 9216e82

**Comment by mcampa** [comment]
Generating bundle for 8a59d9b

**Comment by mcampa** [comment]
Generating bundle for 480d3c3

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/480d3c3cc924b5ffe55b33dbe70385550a1e3a33/bundle.zip) for commit 480d3c3

**Comment by mcampa** [comment]
Generating bundle for 789ae3a

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/789ae3a9123c5b4313c244fbc3689f528e3b35a6/bundle.zip) for commit 789ae3a

**Comment by mcampa** [comment]
Generating bundle for 211f9f5

**Comment by mcampa** [comment]
Generating bundle for 8fc8bb9

**Comment by mcampa** [comment]
Generating bundle for ce68d63

**Comment by mcampa** [comment]
Generating bundle for 4ecffcb

**Comment by mcampa** [comment]
Generating bundle for d479cd3

**Comment by mcampa** [comment]
Generating bundle for 6fb2f1b

**Comment by mcampa** [comment]
Generating bundle for 3a251d7

**Comment by mcampa** [comment]
Generating bundle for 0948592

**Comment by mcampa** [comment]
Generating bundle for 6009acc

**Comment by mcampa** [comment]
Generating bundle for 59ad259

**Comment by mcampa** [comment]
Generating bundle for 1ded239

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/1ded2391668be1ea9bb41e35b222a0eb7d2cfc55/bundle.zip) for commit 1ded239

**Comment by mcampa** [comment]
Generating bundle for b827a4e

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/b827a4e7e2c6832dba84014c181d8ee509686b40/bundle.zip) for commit b827a4e

**Comment by mcampa** [comment]
Generating bundle for a7e1e5d

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/a7e1e5df6fe4917a06c8d0d3c54b0c1e7a61070a/bundle.zip) for commit a7e1e5d

**Comment by stencil-check** [comment]
Generating bundle for e1b8fa5

**Comment by mcampa** [comment]
Generating bundle for a9f646a

**Comment by mcampa** [comment]
Generating bundle for commit 7adb7d3

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/7adb7d3dcfa2c8eb84f33fe8b4c294ed3c2183b4/bundle.zip) for commit 7adb7d3

**Comment by mcampa** [comment]
Generating bundle for commit 59b9119

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/59b9119941bf3f4ea9e5ffd893c95900294a6841/bundle.zip) for commit 59b9119

**Comment by mcampa** [comment]
Generating bundle for commit 343bc33

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/343bc3365770ff861e27731f5ed83aecb4718dc7/bundle.zip) for commit 343bc33

**Comment by mcampa** [comment]
Generating bundle for commit b2cdd99

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/b2cdd99fd4cfc977cd6b5a3bc0810bfe03b43a17/bundle.zip) for commit b2cdd99

**Comment by mcampa** [comment]
Generating bundle for commit 11dfdd8

**Comment by mcampa** [comment]
Generating bundle for commit 50e14c4

**Comment by mcampa** [comment]
Generating bundle for commit 718ab4e

**Comment by mcampa** [comment]
Generating bundle for commit 1870887

**Comment by mcampa** [comment]
Generating bundle for commit b8572ba

**Comment by mcampa** [comment]
Generating bundle for commit ee40c9e

**Comment by mcampa** [comment]
Generating bundle for commit d620ce8

**Comment by mcampa** [comment]
Generating bundle for commit d1a92d4

**Comment by mcampa** [comment]
Generating bundle for commit 5494b0a

**Comment by mcampa** [comment]
Generating bundle for commit ca7a4bb

**Comment by mcampa** [comment]
Generating bundle for commit f73a354

**Comment by mcampa** [comment]
Generating bundle for commit 4aefa37

**Comment by mcampa** [comment]
Generating bundle for commit 41c45c7

**Comment by mcampa** [comment]
Generating bundle for commit eafed48

**Comment by mcampa** [comment]
Generating bundle for commit 4208526

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/4208526d80a3d6fa9dfcf2124f042eacf9088b4a/bundle.zip) for commit 4208526

**Comment by mcampa** [comment]
Generating bundle for commit a554fbd

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/a554fbd82498cfc5006c1ec8d9a6106789c21c10/bundle.zip) for commit a554fbd

**Comment by mcampa** [comment]
Generating bundle for commit 5073c62

**Comment by mcampa** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/5073c62c86317ddc3469e3fda9ab96decbc1c9d7/bundle.zip) for commit 5073c62

**Comment by stencil-check** [comment]
Generating bundle for commit a628212

**Comment by stencil-check** [comment]
Generating bundle for commit 4ab5dd5

**Comment by stencil-check** [comment]
Generating bundle for commit 5a98d78

**Comment by stencil-check** [comment]
Generating bundle for commit 31c2fa4

**Comment by stencil-check** [comment]
Generating bundle for commit 2d98704

**Comment by stencil-check** [comment]
Generating bundle for commit 37ee1e2

**Comment by stencil-check** [comment]
Generating bundle for commit 1c3bfb0

**Comment by stencil-check** [comment]
Generating bundle for commit 408028e

**Comment by stencil-check** [comment]
Generating bundle for commit 4bb02f5

**Comment by stencil-check** [comment]
Generating bundle for commit 527e462

**Comment by stencil-check** [comment]
Generating bundle for commit cf18d6d

**Comment by stencil-check** [comment]
Generating bundle for commit 107ceea

**Comment by stencil-check** [comment]
Generating bundle for commit fd36a6d

**Comment by stencil-check** [comment]
Generating bundle for commit c2b3c6c

**Comment by stencil-check** [comment]
Generating bundle for commit 0be8a51

**Comment by stencil-check** [comment]
Generating bundle for commit 60f9d88

**Comment by stencil-check** [comment]
Generating bundle for commit 100e830

**Comment by stencil-check** [comment]
Generating bundle for commit 7d75e46

**Comment by stencil-check** [comment]
Generating bundle for commit 615f155

**Comment by stencil-check** [comment]
Generating bundle for commit d418018

**Comment by stencil-check** [comment]
Generating bundle for commit a0f2cf3

**Comment by stencil-check** [comment]
Generating bundle for commit f440527

**Comment by stencil-check** [comment]
Generating bundle for commit 0633e48

**Comment by stencil-check** [comment]
Generating bundle for commit 1810f82

**Comment by stencil-check** [comment]
Generating bundle for commit 81d213e

**Comment by stencil-check** [comment]
Generating bundle for commit 8126a2e

**Comment by stencil-check** [comment]
Generating bundle for commit 6bc5323

**Comment by stencil-check** [comment]
Generating bundle for commit ceb50e2

**Comment by stencil-check** [comment]
Generating bundle for commit fd225c8

**Comment by stencil-check** [comment]
Generating bundle for commit 2155328

**Comment by stencil-check** [comment]
Generating bundle for commit 98aa3f2

**Comment by stencil-check** [comment]
Generating bundle for commit e3c8d19

**Comment by stencil-check** [comment]
Generating bundle for commit ef51a06

**Comment by stencil-check** [comment]
Generating bundle for commit be08cd7

**Comment by stencil-check** [comment]
Generating bundle for commit 265eece

**Comment by stencil-check** [comment]
Generating bundle for commit c1c99b0

**Comment by stencil-check** [comment]
Here is the [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/c1c99b091449bf44844af9440d012c69b2d74c3a/theme.zip) for commit c1c99b0

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/07cadaaaefbaeea12e8785ba3a2995ea02f11a6b/theme.zip) for commit 07cadaa

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/4f70e198876e1d88225c7e25f407dfd0f62cb845/theme.zip) for commit 4f70e19

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/84b02d21d4144960c47b81dde82d4bfd61a633c8/theme.zip) for commit 84b02d2

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/a7d30f3ba7c8607f5bcd9d9fad361538aede2673/theme.zip) for commit a7d30f3

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/d4835b061dc978c0be4e6663238b19b0b30af154/theme.zip) for commit d4835b0

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/7511d9d6d03d1985e13ecf93ed90efa6f950026e/theme.zip) for commit 7511d9d

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/e3e1bfa524d6023f516948ad687801d6af45357d/theme.zip) for commit e3e1bfa

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/428885a15e8580553b0a677b726bb8600455caf2/theme.zip) for commit 428885a

**Comment by mcampa** [comment]
Generated [bundle](http://bc-stencil-theme-submission-development.s3.amazonaws.com/stencil-bundles/78498977ac70286dbf4e2ef8789bbf4e8723597e/theme.zip) for commit 7849897

**Comment by mcampam** [comment]
Generated [bundle](http://bc-stencil-theme-submission-integration.s3.amazonaws.com/stencil-bundles/78498977ac70286dbf4e2ef8789bbf4e8723597e/theme.zip) for commit 7849897

**Comment by mcampam** [comment]
Generated [bundle](http://bc-stencil-theme-submission-integration.s3.amazonaws.com/stencil-bundles/793210138eebb2314f5d0a35878209d27a998d93/theme.zip) for commit 7932101

**Pull request closed without merging**
